# See https://www.loraserver.io/lora-app-server/install/config/ for a full
# configuration example and documentation.

[general]
password_hash_iterations=10000

[postgresql]
dsn="postgres://loraserver_as:loraserver_as@localhost/loraserver_as?sslmode=disable"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="Y301pq2kbuKbZHHlrGCsIoiMf7UJAnlEerv8OHYD93Q="
